### PR TITLE
Added .travis.yml

### PR DESCRIPTION
**Pull request by makotoshimazu**
This PR enables us to check that
- the code base sent as a PR can be compiled correctly
- `$ gradlew check` works properly (and this means tests are green)

Additionally, I changed the settings of repositories (drive/drivecommand). This makes following changes:
- when the test fails, merge button will be disabled.
- when owners (PILE members) push some code to `develop` or `master`, the patch will be merged into the branch after testing. If the test fails, merge process will be canceled. (I've not checked it yet, though...)

Issue #8

### CODE REVIEW

**Comment by mandaiy** [comment]
Could you give some URLs of the document you followed?

**Comment by makotoshimazu** [comment]
Sure. Here is the link:
https://docs.travis-ci.com/user/languages/java/

**Comment by mandaiy** [comment]
I had a brief look on the document, but still I'm not sure that with this PR what kind of thing we can do.
Could you list the things we can do? like `we are able to view the test status on this url, prevent from merging ill commits that do not satisfy the test coverage requirements, ...`
Also are there any operations you did outside git? (like on web-browser) 
If so, the information is worth noting in the PR message.

**Comment by makotoshimazu** [comment]
This PR enables us to check that
- the code base sent as a PR can be compiled correctly
- `$ gradlew check` works properly (and this means tests are green)
- such status can be confirmed from a link at README on [the repository page](https://github.com/PileProject/drivecommand)

What I did is to login to TravisCI using my account, and I turned on a switch of integration.
Additionally, I changed the settings of repositories (drive/drivecommand). This makes the following changes:
- when the test fails, merge button will be disabled.
- when owners (PILE members) push some code to `develop` or `master`, the patch will be merged into the branch after testing. If the test fails, merge process will be canceled. (I've not checked it yet, though...)

**Review by mandaiy — APPROVED** [review]

**Comment by makotoshimazu** [comment]
Now is the time to use THE extension, right??
https://chrome.google.com/webstore/detail/lgtm/oeacdmeoegfagkmiecjjikpfgebmalof?hl=ja&gl=JP

**Pull request merged**
